---
kind: pipeline
type: docker
name: install.zerotier.com

platform:
  arch: amd64
  os: linux

clone:
  depth: 1

steps:
  - name: build
    image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/central-builder
    commands:
      - echo $${DOCKER_PASSWORD} | docker login --username $${DOCKER_LOGIN} --password-stdin registry.zerotier.com
      - make docker
      - make push
    environment:
      DOCKER_LOGIN:
        from_secret: docker-registry-login
      DOCKER_PASSWORD:
        from_secret: docker-registry-password
      DOCKER_REGISTRY:
        from_secret: docker-registry-host
  - name: notify-mattermost-build-failure
    pull: always
    image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/mattermost-notify
    depends_on:
      - build
    environment:
      token:
        from_secret: mattermost-token
      host:
        from_secret: mattermost-host
      channel:
        from_secret: mattermost-channel
      maxRetry: 3
    when:
      status:
        - failure
trigger:
  event:
    - push
    - pull_request
    - tag
---
kind: signature
hmac: c424a4e052c47dfad3a5eb4f06baac3381e1fc29a81a02667bd07dcfad29f0f0
